# Generated by Django 5.1.1 on 2025-10-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeuSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=65)),
                ('favicon', models.ImageField(blank=True, default='', null=True, upload_to='dist/media/img/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Meu Site',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
