# Generated by Django 5.1.1 on 2025-10-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblog',
            options={'verbose_name': 'Meu Blog', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AddField(
            model_name='myblog',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='myblog',
            name='show_description',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='show_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='show_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='show_pagination',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='show_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='title',
            field=models.CharField(default='', max_length=65),
        ),
    ]
