# Generated by Django 5.1.1 on 2025-10-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_myblog_options_myblog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='new_tab',
        ),
        migrations.RemoveField(
            model_name='myblog',
            name='text',
        ),
        migrations.RemoveField(
            model_name='myblog',
            name='ur_or_path',
        ),
    ]
