# Generated by Django 5.1.1 on 2025-10-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_myblog_new_tab_remove_myblog_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='favicon',
            field=models.ImageField(blank=True, default='', null=True, upload_to='dist/media/img/%Y/%m/'),
        ),
    ]
